#!/bin/bash
# Check if an IP address is passed as an argument

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the given IP 5 times
ping -c 5 "$1"
